# Generated by Django 4.2.3 on 2023-07-24 01:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, default='static/post-default.png', null=True, upload_to='noticias')),
                ('texto', ckeditor.fields.RichTextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_noticia', models.ManyToManyField(default='Sin Categoria', null=True, to='categorias.categoria')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
